apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: capsule_db
  MYSQL_USER: capsule_user
  MYSQL_PASSWORD: capsule_password

---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: retail-ns
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretMapKeyRef:
                  name: retail-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                secretMapKeyRef:
                  name: retail-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretMapKeyRef:
                  name: retail-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretMapKeyRef:
                  name: retail-secret
                  key: MYSQL_USER
  
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: retail-ns
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP



