apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: retail-ns
spec:
  storageClassName: nf-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi