apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-retail-pvc
  namespace: retail-ns
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-retail
 